version: "2"

services:
  ss:
    image: grugway/sss
    environment:
      - PASSWORD=your_ss_password
    restart: always

  kcp:
    image: grugway/kcps
    depends_on:
      - "ss"
    environment:
      - KEY=your_kcp_key
      - REMOTE_DOMAIN=ss
      - REMOTE_PORT=8388
    ports:
      - "your_kcp_port:29900/udp"
    restart: always

  usp:
    image: grugway/usps
    depends_on:
      - "ss"
    environment:
      - KEY=your_usp_key
      - REMOTE_DOMAIN=ss
      - REMOTE_PORT=8388
    ports:
      - "your_usp_port:29901/udp"
    restart: always
